### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by Julien851** [perceptron8/pinky.cr#4]
Is the availability of the extension planned for Firefox or MS Edge?

**Comment by perceptron8** [comment]
**Firefox**

Everything is more than ready! See:
* https://github.com/perceptron8/pinky.ff

Everyting... except Firefox. There is one awful bug that need to be fixed:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1114891

The issue has been reported (by me) almost one year ago. Since then, there's almost no progress. It looks like FF44+ works well, but that hasn't been confirmed - so it's very likely that something will break one day. Right now, I'm stuck. In case of any problems, people will blame me - not Mozilla, nor Adobe. I have to wait.

It would be really nice if you follow this last link/thread and let Mozilla's people know if sample extension works for you.

**MS Edge**
As soon as extensions are available, I'll try to write one! It's impossible now. See:
* http://windows.microsoft.com/en-US/windows-10/extensions-in-microsoft-edge

**Comment by Julien851** [comment]
Thanks for your answer :-)
I know for MS Edge. Extension will be available with Red Stone.
How can I help you for Firefox?

**Comment by perceptron8** [comment]
If you have or could have Firefox 44 (it's currently in beta), please review
https://bugzilla.mozilla.org/show_bug.cgi?id=1114891

Here's most recent sample add-on I made for testing:
https://bugzilla.mozilla.org/attachment.cgi?id=8686205

Here's flash app demo loading some images:
http://www.adobe.com/devnet/actionscript/samples/media_2.html

With add-on installed (and redirection working properly), you should see pink rectangles instead of original images. One more thing... It's important clear cache before tests!

**Comment by Julien851** [comment]
It works for me with Firefox 44.0b1. The left-half of the image is pink and the right-half is grey.

**Comment by perceptron8** [comment]
Thanks, that's great! Please, if you can, add a comment at bugzilla too.

**Comment by Julien851** [comment]
Done, with a attachment.

**Comment by perceptron8** [comment]
I've just uploaded Firefox add-on. It should work with beta (44.0b1). I used nightly (45.0a2). It seems to work, but I needed to clear cache twice. Once again, I invite you to:

https://github.com/perceptron8/pinky.ff

All installation links there. If there will be another issues with Firefox, please, use that project.

Good luck! :-)

PS. Thanks for help!

**Comment by Julien851** [comment]
It works on TSO too :-)

**Comment by perceptron8** [comment]
That's not the same add-on, but - yeah - it works :-) That's another Pinky!

**Comment by Julien851** [comment]
No more works on Firefox :(
![capture2](https://cloud.githubusercontent.com/assets/16362873/12152642/03cbadea-b4b6-11e5-8d0b-110ecf9132e0.PNG)

**Comment by Julien851** [comment]
![capture2](https://cloud.githubusercontent.com/assets/16362873/12152732/69b41c14-b4b6-11e5-9ed7-fb1978cfd2d8.PNG)

**Comment by perceptron8** [comment]
Sadly, that's true. You can watch eventual progress here:
https://github.com/perceptron8/pinky.ff/issues/1
Please, let me know (and please, post it at pinky.ff), what versions of Flash and Firefox are you using.

**Comment by perceptron8** [comment]
Firefox is finally supported! :) But there's one catch. You need to make sure that you have Electrolysis (e10s) enabled. See https://wiki.mozilla.org/Electrolysis#Firefox_Release for details. Good luck!

**Comment by perceptron8** [comment]
Please visit https://github.com/perceptron8/pinky.ext#where to get installation url for your favorite browser.
