### ISSUE TITLE
Slim browser support

### ISSUE THREAD

**Issue by KarrokDC** [perceptron8/pinky.cr#6]
Hi,

Is it possible to somehow use this plugin in the stand-alone client (chromium/NW.js based afaik) ?

Thanks in advance

**Comment by perceptron8** [comment]
Hi,

After quick research, I tried adding `--load-extension=/path/to/unpacked/pinky` into `package.json`, but that gave me nothing. And even if it had worked, it would be rather dirty hack. Can't say if TSO SC uses some old NW.js (with no `--load-extension` support) or `chrome.webRequest` API is not supported, or is it something else.

I'm not sure also, if I would like to support this kind of setup. Pinky's motivation was to create something easy to install (with one click preferably). I don't believe that something similar can be done for TSO SC. Prove I'm wrong, If you like!

You may like to search for alternative solutions. I know that there exist programs modifying browser's cache in a way that instead of collectible you get some more visible image... That's just one idea. I hope you will find something appropriate.

**Comment by t00tie** [comment]
I would love to see support for the Steam version., is that the same as this? Could you point us in the right direction eg. which file to copy?

**Comment by perceptron8** [comment]
@t00tie I suppose that Steam version of TSO is just some kind of swf launcher, so there is no browser, thus you can't use any extensions, including Pinky.
